version: '3'
services:
  db:
    networks:
      - appnet
    build:
      context: ./services/db
    ports:
      - "5432:5432"
    volumes:
      - ./services/db/data:/var/lib/postgresql/data
  web:
    networks:
    - appnet
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      NODE_ENV: development
    command: node server
  main-api:
    networks:
    - appnet
    build:
      context: ./services/main-api
    ports:
      - "3001:3001"
    volumes:
      - ./services/main-api:/app
    depends_on:
      - db
    command: node_modules/nodemon/bin/nodemon.js index.js
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
