version: '3'
services:
  ts-web:
    networks:
    - appnet
    build:
      context: ./ts-web
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./ts-web:/app
    environment:
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      NODE_ENV: development
    command: "node /app/node_modules/.bin/webpack-dev-server --debug --devtool cheap-module-source-map --output-pathinfo --history-api-fallback --hot --inline --progress --colors --port 3000 --host 0.0.0.0"
  main-api:
    networks:
    - appnet
    build:
      context: ./services/main-api
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    volumes:
      - ./services/main-api:/app
    environment:
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      NODE_ENV: development
    command: node_modules/nodemon/bin/nodemon.js index.js
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
