db:
  host: localhost
  name: prayer_praise_app_dev
  user: postgresdev
  password: postgresdev
api:
  host: 'localhost'
  port: 3001
  cors: true
token:
  secret: das34rtji89y676768ghjtt78ikiy9ufg4dasdam4l30434kmr34r8dgfgdtj54n4334gtr5
